# Generated by Django 2.0.6 on 2020-03-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DOrderiterm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_num', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'd_orderiterm',
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=128, null=True)),
                ('book_author', models.CharField(blank=True, max_length=64, null=True)),
                ('book_publish', models.CharField(blank=True, max_length=128, null=True)),
                ('publish_time', models.DateField(auto_now_add=True, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('book_isbn', models.CharField(blank=True, max_length=64, null=True)),
                ('word_count', models.CharField(blank=True, max_length=64, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('open_type', models.CharField(blank=True, max_length=20, null=True)),
                ('book_paper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_wrapper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_category', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('book_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('book_dprice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('editor_recommendation', models.TextField(blank=True, null=True)),
                ('content_introduction', models.TextField(blank=True, null=True)),
                ('author_introduction', models.TextField(blank=True, null=True)),
                ('menu', models.TextField(blank=True, null=True)),
                ('media_review', models.TextField(blank=True, null=True)),
                ('digest_image_path', models.TextField(blank=True, null=True)),
                ('product_image_path', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('series_name', models.CharField(blank=True, max_length=128, null=True)),
                ('printing_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('impression', models.CharField(blank=True, max_length=64, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('shelves_date', models.DateField(auto_now_add=True, null=True)),
                ('customer_socre', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('book_status', models.IntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('cate_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order_addrid', models.IntegerField(null=True)),
                ('order_uid', models.IntegerField(null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('t_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexapp.TAddress')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_num', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexapp.TBook')),
            ],
            options={
                'db_table': 't_shipping',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('user_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='tshipping',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexapp.TUser'),
        ),
        migrations.AddField(
            model_name='torder',
            name='t_u',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexapp.TUser'),
        ),
        migrations.AddField(
            model_name='tbook',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexapp.TCategory'),
        ),
        migrations.AddField(
            model_name='taddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexapp.TUser'),
        ),
        migrations.AddField(
            model_name='dorderiterm',
            name='shop_bookid',
            field=models.ForeignKey(db_column='shop_bookid', on_delete=django.db.models.deletion.DO_NOTHING, to='indexapp.TBook'),
        ),
        migrations.AddField(
            model_name='dorderiterm',
            name='shop_ordid',
            field=models.ForeignKey(blank=True, db_column='shop_ordid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexapp.TOrder'),
        ),
    ]
