# Generated by Django 2.0.6 on 2020-03-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorderiterm',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dorderiterm',
            name='uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
