# Generated by Django 2.0.6 on 2020-03-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_auto_20200304_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dorderiterm',
            old_name='user_id',
            new_name='users_id',
        ),
    ]
