# Generated by Django 2.0.6 on 2020-03-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_auto_20200304_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taddress',
            old_name='user',
            new_name='user_id',
        ),
    ]
