# Generated by Django 2.0.6 on 2020-03-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_auto_20200305_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taddress',
            old_name='user_id',
            new_name='user',
        ),
    ]
